// examples/react-simple/src/App.tsx
import { IntlMessageFormat } from "intl-messageformat";
import { useState } from "react";
import type { FormEvent } from "react";

import { tpath } from "../../../tpath.ts";
import { en } from "./translations/en";
import { ru } from "./translations/ru";
import type { Messages } from "./translations/types";

type Translations = typeof en;

interface TranslationContext {
  readonly debug: boolean;
  readonly locale: string;
  readonly messages: Messages<Translations>;
}

export const createT = tpath<Translations>()
  .ctx<TranslationContext>()
  .define({
    $exists(ctx, child?: string) {
      const nextKeys = child === undefined ? ctx.keys : [...ctx.keys, child];

      return resolveNested(ctx.messages, nextKeys) !== undefined;
    },
    __call(ctx, keys, interpolation) {
      if (ctx.debug) {
        return keys.join(".");
      }

      const message = resolveNested(ctx.messages, keys);

      if (message === undefined) {
        return undefined;
      }

      return new IntlMessageFormat(message, ctx.locale, undefined, { ignoreTag: true }).format(
        interpolation as any,
      ) as string;
    },
  });

const translations = {
  en,
  ru,
} as const;

type Locale = keyof typeof translations;

interface AppProps {
  readonly initialLocale?: Locale;
}

export function App({ initialLocale = "en" }: AppProps = {}) {
  const [locale, setLocale] = useState<Locale>(initialLocale);
  const [debug, setDebug] = useState(false);
  const [notes, setNotes] = useState<readonly string[]>([]);
  const [text, setText] = useState("");
  const t = createT({
    debug,
    locale,
    messages: translations[locale],
  });

  function toggleDebug() {
    setDebug((currentDebug) => !currentDebug);
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const nextText = text.trim();

    if (nextText.length === 0) {
      return;
    }

    setNotes((currentNotes) => [...currentNotes, nextText]);
    setText("");
  }

  return (
    <main className="simple-app">
      <header>
        <h1>{t.app.title()}</h1>
        <div className="header-controls">
          <label>
            {t.app.localeSelect.label()}
            <select
              value={locale}
              onChange={(event) => {
                setLocale(event.currentTarget.value as Locale);
              }}
            >
              <option value="en">{t.app.localeSelect.en()}</option>
              <option value="ru">{t.app.localeSelect.ru()}</option>
            </select>
          </label>
          <button type="button" onClick={toggleDebug}>
            {debug ? t.app.debugToggle.hide() : t.app.debugToggle.show()}
          </button>
        </div>
      </header>

      <form onSubmit={submit}>
        <label htmlFor="note">{t.app.form.label()}</label>
        <input
          id="note"
          placeholder={t.app.form.placeholder.$exists() ? t.app.form.placeholder() : undefined}
          value={text}
          onChange={(event) => setText(event.currentTarget.value)}
        />
        <button type="submit">{t.app.form.submit()}</button>
      </form>

      <section aria-live="polite">
        {notes.length === 0 ? (
          <p>{t.app.notes.empty()}</p>
        ) : (
          <>
            <p>{t.app.notes.count({ count: notes.length })}</p>
            <ul>
              {notes.map((note, index) => (
                <li key={`${note}:${index}`}>
                  {t.app.notes.item({ index: index + 1, text: note })}
                </li>
              ))}
            </ul>
          </>
        )}
      </section>
    </main>
  );
}

function resolveNested(messages: Messages<Translations>, keys: readonly string[]) {
  let value: unknown = messages;

  for (const key of keys) {
    if (!isRecord(value)) {
      return undefined;
    }

    value = value[key];
  }

  return typeof value === "string" ? value : undefined;
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null;
}

// examples/vue-simple/src/App.vue
<script lang="ts">
import { IntlMessageFormat } from "intl-messageformat";
import { tpath } from "../../../tpath.ts";
import { en } from "./translations/en";
import { ru } from "./translations/ru";
import type { Messages } from "./translations/types";

type Translations = typeof en;
type Accessor<T> = () => T;

interface TranslationContext {
  readonly debug: Accessor<boolean>;
  readonly locale: Accessor<string>;
  readonly messages: Accessor<Messages<Translations>>;
}

export const createT = tpath<Translations>()
  .ctx<TranslationContext>()
  .define({
    $exists(ctx, child?: string) {
      const nextKeys = child === undefined ? ctx.keys : [...ctx.keys, child];

      return resolveNested(ctx.messages(), nextKeys) !== undefined;
    },
    __call(ctx, keys, interpolation) {
      if (ctx.debug()) {
        return keys.join(".");
      }

      const message = resolveNested(ctx.messages(), keys);

      if (message === undefined) {
        return undefined;
      }

      return new IntlMessageFormat(message, ctx.locale(), undefined, { ignoreTag: true }).format(
        interpolation as any,
      ) as string;
    },
  });

const translations = {
  en,
  ru,
} as const;

type Locale = keyof typeof translations;

function resolveNested(messages: Messages<Translations>, keys: readonly string[]) {
  let value: unknown = messages;

  for (const key of keys) {
    if (!isRecord(value)) {
      return undefined;
    }

    value = value[key];
  }

  return typeof value === "string" ? value : undefined;
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null;
}
</script>

<script setup lang="ts">
import { ref } from "vue";

defineOptions({
  name: "App",
});

const props = withDefaults(
  defineProps<{
    readonly initialLocale?: Locale;
  }>(),
  {
    initialLocale: "en",
  },
);

const locale = ref<Locale>(props.initialLocale);
const debug = ref(false);
const notes = ref<readonly string[]>([]);
const text = ref("");
const t = createT({
  debug: () => debug.value,
  locale: () => locale.value,
  messages: () => translations[locale.value],
});

function toggleDebug() {
  debug.value = !debug.value;
}

function submit() {
  const nextText = text.value.trim();

  if (nextText.length === 0) {
    return;
  }

  notes.value = [...notes.value, nextText];
  text.value = "";
}
</script>

<template>
  <main class="simple-app">
    <header>
      <h1>{{ t.app.title() }}</h1>
      <div class="header-controls">
        <label>
          {{ t.app.localeSelect.label() }}
          <select v-model="locale">
            <option value="en">{{ t.app.localeSelect.en() }}</option>
            <option value="ru">{{ t.app.localeSelect.ru() }}</option>
          </select>
        </label>
        <button type="button" @click="toggleDebug">
          {{ debug ? t.app.debugToggle.hide() : t.app.debugToggle.show() }}
        </button>
      </div>
    </header>

    <form @submit.prevent="submit">
      <label for="note">{{ t.app.form.label() }}</label>
      <input
        id="note"
        v-model="text"
        :placeholder="t.app.form.placeholder.$exists() ? t.app.form.placeholder() : undefined"
      />
      <button type="submit">{{ t.app.form.submit() }}</button>
    </form>

    <section aria-live="polite">
      <p v-if="notes.length === 0">{{ t.app.notes.empty() }}</p>
      <template v-else>
        <p>{{ t.app.notes.count({ count: notes.length }) }}</p>
        <ul>
          <li v-for="(note, index) in notes" :key="`${note}:${index}`">
            {{ t.app.notes.item({ index: index + 1, text: note }) }}
          </li>
        </ul>
      </template>
    </section>
  </main>
</template>
